version: '3'
services:
  api:
    image: todo-app-express
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"

  web-cli:
    image: todo-app-express
    networks:
      - backend
    command: sh

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/todo_db -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db

volumes:
  db:

networks:
  backend:
    driver: bridge
