version: '3'
services:
  api:
    image: todo-app-express
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"

  web-cli:
    image: todo-app-express
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
