name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
defaults:
  run:
    working-directory: ui

jobs:
#  execute:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 🛎 Checkout
#        uses: actions/checkout@v3
#      - name: Start docker compose
#        run: docker compose --profile dev up -d --wait && sleep 30
#      - name: Test
#        run:  npm run test
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
      #needs: [ execute ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm i
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
